### ISSUE TITLE
prepare image/flist for 3bot version of gitea 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-gitea#5]
- should live in tf-images

**Comment by Pishoy** [comment]
flist done in docker hub `threefolddev/gitea_all_in_one`
but still waiting this issue https://github.com/threefoldtech/tf-gitea/issues/8

**Comment by Pishoy** [comment]
verifed

**Comment by Pishoy** [comment]
flist updated https://hub.grid.tf/bishoy.3bot/threefolddev-gitea_all_in_one-latest.flist
