### ISSUE TITLE
can not login with admin account after initializating  setup

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/tf-gitea#8]
- server setup is done and we create an admin account as per below screen shot
![image](https://user-images.githubusercontent.com/21987477/87542191-d9d77880-c6a2-11ea-83eb-7d42422962d1.png)

- the issue now, we can not log in by admin user that was created while setup gitea as the default login is 3bot 

- can we create a directive like ip/admin to login with admin user/pass instead default login 3bot ?

**Comment by alichaddad** [comment]
Handled [here](https://github.com/threefoldtech/tf-gitea/commit/868befa6c2ac6f9c5e5bdf0efe63095073e105e9).
Admin can login using endpoint `/user/admin`.

**Comment by Pishoy** [comment]
verifed
